source 'https://gems.ruby-china.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'rake-hooks'
gem 'require_all'
gem 'bunny'

gem 'pry'
gem 'pry-byebug'
gem 'sqlite3'
gem 'minitest'
gem 'test-unit'
gem 'rack-test'
gem 'database_cleaner'
gem 'factory_girl'